---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asiddiqui6
resources:
  - ../../base
  - virtual-service.yaml
  - hpa-api.yaml
images:
  - name: lab4
    newName: w255mids.azurecr.io/asiddiqui6/lab4
    newTag: "1234"
