---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: external-access
spec:
  hosts:
    - asiddiqui6.mids255.com
  gateways:
    - istio-ingress/asiddiqui6-gateway
  http:
    - match:
        - uri:
            prefix: /lab
      route:
        - destination:
            host: lab-prediction-service
            port:
              number: 8000
